
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: africloud
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/africloud
      - JWT_SECRET=change_this_secret
      - AWS_REGION=us-east-1
      - S3_BUCKET=africloud-bucket
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  db-data:
